export const START_FETCHING = "START_FETCHING";
export const STOP_FETCHING = "STOP_FETCHING";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const DO_LOGIN = "DO_LOGIN";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USER_DATA = "SET_USER_DATA";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_MOVEMENTS = "SET_MOVEMENTS";
export const SET_TOTAL = "SET_TOTAL";
export const SET_FILTERED_MOVEMENTS = "SET_FILTERED_MOVEMENTS";
export const CLEAR_FILTERED_MOVEMENTS = "CLEAR_FILTERED_MOVEMENTS";
